### ISSUE TITLE
Timetable issue with group IB3C

### ISSUE THREAD

**Issue by JulianWagner91** [Fachschaft07/fs-app#37] opened 2015-09-30 14:55 UTC
not able to select the schedule for group IB3C

**Comment by FHellmann** [comment] 2015-10-01 09:11
This should be fixed with the next [rest-service update](https://github.com/Fachschaft07/fs-rest/pull/40).

**Comment by jqbbq** [comment] 2015-10-01 13:44
This is now fixed in the rest-service. Unfortunately the App ist still crashing when loading the modules for IB3C. 

This could be the result of an null value in the the response for an teacher.

**Comment by FHellmann** [comment] 2015-10-01 13:48
I will have a look at it.

**Comment by FHellmann** [comment] 2015-10-04 09:42
I think this is the following exception stacktrace for the issue:

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String edu.hm.cs.fs.common.model.simple.SimplePerson.getId()' on a null object reference
	at edu.hm.cs.fs.app.database.model.TimetableModel.getLessonGroupId(TimetableModel.java:273)
	at edu.hm.cs.fs.app.database.model.TimetableModel.isModuleSelected(TimetableModel.java:286)
	at edu.hm.cs.fs.app.presenter.TimetableEditorPresenter.isLessonGroupSelected(TimetableEditorPresenter.java:62)
	at edu.hm.cs.fs.app.ui.timetable.TimetableEditorAdapter$ViewHolder.init(TimetableEditorAdapter.java:95)
	at edu.hm.cs.fs.app.ui.timetable.TimetableEditorAdapter.onBindViewHolder(TimetableEditorAdapter.java:63)
	at edu.hm.cs.fs.app.ui.timetable.TimetableEditorAdapter.onBindViewHolder(TimetableEditorAdapter.java:29)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5277)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5310)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4568)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4461)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1962)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1371)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1334)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:563)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2847)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3145)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:581)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1034)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:744)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1180)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:757)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15671)
	at android.view.ViewGroup.layout(ViewGroup.java:5038)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by FHellmann** [comment] 2015-10-09 11:54
@jqbbq the issue is a result of the query parameter. Because the rest service want to see 3 parameters (group, module and teacher). I only can send group and module, teacher would be empty and this doesn't work.

See this url: http://fs.cs.hm.edu/rest/api/1/timetable/lessons?group=IB3C&module=marketing&teacher=

**Closed** 2015-10-11 14:28 UTC
Labels: bug, in progress, waiting for rest support
